// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkyldwsgagbkrshqfawi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhreWxkd3NnYWdia3JzaHFmYXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzOTcwMDMsImV4cCI6MjA1NDk3MzAwM30.ez9qFcGO6TYuYstugoo8r_zTyMzvxAs7sXZM5ygcBpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);